import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Provider from "./Provider";
import Header from "./(components)/Header";
import {Nunito} from 'next/font/google';

const myAppFont = Nunito({subsets: ['latin']});

export const metadata: Metadata = {
  title: "AI Story Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={myAppFont.className}
      >
        <Provider>
        <Header/>
        {children}
        </Provider>        
      </body>
    </html>
  );
}
